### PR TITLE
update properties.language to an object per latest OARec changes

### PR DESCRIPTION
**Pull request by tomkralidis**
Update WCMP2 language to be an object (not a string) per latest OGC API - Records updates.

### CODE REVIEW

**Review by maaikelimper — COMMENTED** [review]
Has this been tested locally ? I am not sure if this works in vue

**Comment by maaikelimper** [comment]
@alimand can you try to test locally if this PR from Tom works as intended ?

**Comment by alimand** [comment]
@maaikelimper Yes, let me have a test

**Comment by alimand** [comment]
it works on my local environment
test

**Review by alimand — APPROVED** [review]
It works on my local environment.

image

**Pull request merged**
