### PR TITLE
Marine templates

### PR DESCRIPTION
**Pull request by david-i-berry**
Addition of WCMP2 metadata templates for drifters and ship based surface weather observations.

### CODE REVIEW

**Comment by tomkralidis** [comment]
@david-i-berry could we have used the MCF format here for the template?  This would ensure / increase compatibility between various workflows in wis2box.

**Comment by maaikelimper** [comment]
I have deployed this on the test-server, the label for ship-hourly-template is incorrect leading to duplicate labels in the dropdown:
image

**Comment by maaikelimper** [comment]
The dropdown is fixed, I created 2 new datasets using the templates:
image

@tomkralidis can you please review the result is as intended:
https://wis2box-test.wis2dev.io/oapi/collections/discovery-metadata/items/urn:wmo:md:io-wis2dev-test2:core.surface-based-observations.ship-hourly
https://wis2box-test.wis2dev.io/oapi/collections/discovery-metadata/items/urn:wmo:md:io-wis2dev-test2:core.surface-based-observations.drifting-buoys.PROGRAM

**Comment by tomkralidis** [comment]
@maaikelimper can you the links as published via MinIO (which is what is sent to WIS2 proper)?  I am also seeing that, in both examples, `properties.themes[0].scheme` is an array of one string, which instead should be a string, so:

```json
        "themes": [
            {   
                "concepts": [
                    {   
                        "id": "weather",
                        "title": "Weather"
                    }   
                ],  
                "scheme": "http://codes.wmo.int/wis/topic-hierarchy/earth-system-discipline"
            }   
        ],  
```

**Comment by maaikelimper** [comment]
Here are the public href links are requested:
https://wis2box-test.wis2dev.io/data/metadata/urn:wmo:md:io-wis2dev-test2:core.surface-based-observations.ship-hourly.json
https://wis2box-test.wis2dev.io/data/metadata/urn:wmo:md:io-wis2dev-test2:core.surface-based-observations.drifting-buoys.PROGRAM.json

Please note that the problem you reported, about the scheme needing to be a string not an array, is unrelated to this PR, the same can be seen for other datasets using the existing synop template:
https://wis2box-test.wis2dev.io/data/metadata/urn:wmo:md:io-wis2dev-test2:surface-based-observations.synop.json

**Comment by tomkralidis** [comment]
Thanks.  I've opened https://github.com/wmo-im/wis2box/issues/728 to track the WCMP2 encoding fix.

**Review by tomkralidis — APPROVED** [review]

**Pull request merged**
